---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: whatsckup-input-pv
spec:
  capacity:
    storage: 50Gi
  accessModes: [ReadOnlyMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: <NFS_SERVER>
    path:   <UPLOAD_PATH>    # crypt15 + Media/ + contacts.vcf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whatsckup-input-pvc
  namespace: whats
spec:
  accessModes: [ReadOnlyMany]
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  volumeName: whatsckup-input-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: whatsckup-app-pv
spec:
  capacity:
    storage: 50Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: <NFS_SERVER>
    path:   <DATA_PATH>      # master DB (msgstore.db, wa.db)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whatsckup-app-pvc
  namespace: whats
spec:
  accessModes: [ReadWriteMany]
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  volumeName: whatsckup-app-pv
